global_costmap:
  global_frame: map
  robot_base_frame: robot_footprint

  update_frequency: 20.0
  publish_frequency: 20.0
  transform_tolerance: 0.5

  width: 100.0
  height: 100.0
  
  static_map: true
